variable "learn_resource_group_name" {
  description = "Name of automatically generated resource group for the Microsoft Learn exercise/sandbox"
  # Using this as a variable also makes it easier to use this template on resource groups not auto-generated by Learn.
}

variable "learn_resource_group_location" {
  description = "Location of automatically generated resource group for the Microsoft Learn exercise/sandbox"
  default = "westus" # my default region, although I imagine it changes based on detected location
}

variable "learn_created_for_value" {
  description = "Value of automatically generated tag on Microosft Learn exercise/sandbox resource group."
}

variable "domain_name_label" {
  description = "Domain name label for the Public IP address resource (which will be used for easier testing/accessing the load-balanced site)"
}