variable "learn_resource_group_name" {
  description = "Name of automatically generated resource group for the Microsoft Learn exercise/sandbox"
  # Using this as a variable also makes it easier to use this template on resource groups not auto-generated by Learn.
}

variable "learn_resource_group_location" {
  description = "Location of automatically generated resource group for the Microsoft Learn exercise/sandbox"
  default = "westus" # my default region, although I imagine it changes based on detected location
}

variable "learn_created_for_value" {
  description = "Value of automatically generated tag on Microosft Learn exercise/sandbox resource group."
}

variable "storage_account_name" {
  validation {
    condition = length(var.storage_account_name) > 2 && length(var.storage_account_name) < 25
    error_message = "Name must be unique across all existing storage account names in Azure. Name must be 3 to 24 characters long and can contain only lowercase letters and numbers."
  }
}

variable "storage_account_location" {
  description = "The free sandbox allows you to create resources in a subset of the Azure global regions."
  # https://docs.microsoft.com/en-us/learn/modules/create-azure-storage-account/5-exercise-create-a-storage-account
  validation {
    condition = contains([
      "West US 2",
      "South Central US",
      "Central US",
      "East US",
      "West Europe",
      "Southeast Asia",
      "Japan East",
      "Brazil South",
      "Austrailia Southeast",
      "Central India"
    ], var.storage_account_location)
    error_message = "Select a region from the following list: \"West US 2\", \"South Central US\", \"Central US\", \"East US\", \"West Europe\", \"Southeast Asia\", \"Japan East\", \"Brazil South\", \"Austrailia Southeast\", \"Central India\"."
  }
}